# Numpy

## Introduction

NumPy’s main object is the **homogeneous multidimensional array**.

In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

NumPy also includes a wide range of mathematical functions and has a wide range of applications in Data Science and Machine Learning.

## Installing Numpy

If you have `Python` and `PIP` already installed on a system, simply run the following command in the terminal.

```
pip install numpy
```

**NOTE:** *Some IDEs such as Anaconda and Google Colab already has Numpy and various other commonly used packages installed.*

## Importing Numpy

We can import Numpy in python using the import keyword.

In [8]:
import numpy

Though, Numpy is usually imported under the `np` alias.

In [10]:
import numpy as np

## Creating Numpy Arrays

The array object in NumPy is called `ndarray`.

### Creating from a Python List and Tuple

You can create an Numpy `ndarray` from a regular Python list or tuple using the `array()` function. 

In [15]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Creating a Numpy `ndarray` with `np.arange()`

`np.arange()` works almost exactly like the basic python `range()` function.

`np.arange()` function returns an array with values within a specified interval.

In [19]:
arr = np.arange(5)

print(arr)

[0 1 2 3 4]


In [20]:
arr = np.arange(2, 6,)

print(arr)

[2 3 4 5]


In [21]:
arr = np.arange(2, 20, 3)

print(arr)

[ 2  5  8 11 14 17]


### Creating a Numpy `ndarray` using `np.zeros()` and `np.ones()`

The `np.zeros()` function allows us to create an array filled with all zeros. Similarly, the `np.ones()` function allows us to create an array filled with all ones. You only need to specify the shape of the array in a tuple (or a single positive integer if it is a 1D array).

In [24]:
arr = np.zeros(4)

print(arr)

[0. 0. 0. 0.]


In [25]:
arr = np.ones((2, 3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


## N-Dimensional Arrays

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

|  1  |  5  |  2  |  0  |
|:---:|:---:|:---:|:---:|

A two-dimensional array would be like a table:

|  1  |  5  |  2  |  0  |
|:---:|:---:|:---:|:---:|
|  8  |  3  |  6  |  1  |
|  1  |  7  |  2  |  9  |

A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages.

NumPy `ndarray` have some restrictions. For instance:

- All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.



## Ndarray Attributes

In [29]:
a = np.array([[5, 7, 0],[0, 1, 9]])

print(a)

[[5 7 0]
 [0 1 9]]


### `ndim` Attribute

The number of dimensions of an array is contained in the `ndim` attribute.

In [32]:
a.ndim

2

### `shape` Attribute

The `shape` of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [35]:
a.shape

(2, 3)

### `size` Attribute

The fixed, total number of elements in array is contained in the `size` attribute. This is the product of the elements of the array’s shape.

In [38]:
a.size

6

### `dtype` Attribute

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the `dtype` attribute.

In [41]:
a.dtype

dtype('int32')

In [42]:
## eye method:

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
## Reshape method: changes the shape of an array ithout changing

In [46]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
## checking the dimention of the array

numbers.ndim

1

In [48]:
##reshape the numbers:reshape one dimensional array to 2 dimentions only
numbers.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [49]:
numbers.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [50]:
names = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10,], [11, 12, 13, 14,15]]]
names

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]

In [51]:
np.array(names).reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [52]:
##flatten method

In [53]:
##linespace: creates nubers of equal interval and must take 3 aurguements

np.linspace(0, 10, 5)
## 0 should be the lowest number in the array, 10 should be the highest number in the array, 
## and 5 should be the total number od numbers in the array.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [54]:
## arange method:

np.arange(1, 102)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101])

In [55]:
np.arange(1, 102, 2) ## 1 IS THE LOWEST VALUE, 102 IS THE HIGHEST NUMBER, WHILE 2 IS THE SPACING INTERVAL

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 101])

In [56]:
##random.rand() method
np.random.rand()

0.5707965170727552

In [57]:
np.random.rand(5)

array([0.19572844, 0.55304264, 0.96253662, 0.5190409 , 0.76539042])

In [58]:
np.random.rand(3, 5)

array([[0.03691958, 0.5281013 , 0.51142193, 0.29237345, 0.68097336],
       [0.27025206, 0.68937357, 0.99816706, 0.23345237, 0.70521121],
       [0.93901886, 0.81664227, 0.82326376, 0.15074044, 0.86803376]])

In [59]:
np.random.rand(2, 3, 4) ### 2 is the no of rows in thr block,
                        ##  3 how many colomns in each block
                        ##  4 is the number of items in eacch row

array([[[0.93166751, 0.2483711 , 0.49840268, 0.24259519],
        [0.06385469, 0.84621127, 0.90298001, 0.31067005],
        [0.03010411, 0.78732196, 0.32413455, 0.93572634]],

       [[0.13503445, 0.97050455, 0.49719428, 0.47426492],
        [0.04134369, 0.88333346, 0.99874336, 0.08612949],
        [0.81477928, 0.49088781, 0.70655078, 0.53318654]]])

In [60]:
np.random.rand(3, 3, 4)

array([[[0.42702027, 0.45884056, 0.75480147, 0.06644403],
        [0.54131163, 0.93163385, 0.25956808, 0.06991586],
        [0.08665859, 0.19616375, 0.35234244, 0.22103067]],

       [[0.37751584, 0.34034325, 0.37572941, 0.10375654],
        [0.19131584, 0.06773767, 0.27648144, 0.35911478],
        [0.57107164, 0.97584263, 0.47436571, 0.57399096]],

       [[0.17810068, 0.39667803, 0.88834416, 0.38755732],
        [0.7549676 , 0.85514704, 0.85989949, 0.2938552 ],
        [0.41177166, 0.84677533, 0.27695585, 0.18839246]]])

In [61]:
np.random.rand(3, 3, 4).ndim

3

In [62]:
np.random.rand(2, 3, 4).ndim

3

In [63]:
np.random.randint(2, 3, 4) ## The lowest number should be 2, not higher than 3, and maximum of 4 values

array([2, 2, 2, 2])

In [64]:
np.random.randint(1, 900, 5)

array([159, 871, 218, 771, 845])

In [65]:
np.random.randint(1, 900, size =(3, 4, 2,)) 
                            

array([[[163, 809],
        [384,  40],
        [788, 496],
        [467, 540]],

       [[812, 569],
        [771, 870],
        [677, 272],
        [779, 309]],

       [[ 99, 702],
        [496, 843],
        [521, 653],
        [ 99,  41]]])

In [66]:
##Statistical Computation


In [67]:
## A. finding mean using numpy

ages =[34, 37, 17, 47, 63, 35, 25, 53,25] ## list of ages of people
arra_ages = np.array(ages)  ## convert the list into a numpy array
average_age=np.mean(arra_ages) ## find the mean of the value of array and store it it a variable called average_age
print(average_age)

37.333333333333336


In [68]:
print(average_age.round(0))

37.0


In [69]:
print("the average age is:", average_age.round(0), "years")

the average age is: 37.0 years


In [70]:
## B. finding median using numpy

In [71]:
ages =[34, 37, 17, 47, 63, 35, 25, 53, 25]
arra_ages =np.array(ages)
median_age =np.median(arra_ages)
print(median_age)
                   

35.0


In [72]:
## Find mode using numpy

from scipy import stats
mode = stats.mode(arra_ages)
print(mode)

ModeResult(mode=25, count=2)


In [73]:
ages =[34, 37, 17, 47, 63, 35, 25, 53,]
mode = stats.mode(arra_ages)
print(mode)

ModeResult(mode=25, count=2)


In [74]:
size = [10, 11, 12, 13, 14, 15, 18, 19, 20, 11, 12, 21]
arr_size = np.array(size)

In [75]:
median_arr =np.median(arr_size)
median_arr

13.5

In [76]:
mode = stats.mode(arr_size)
mode

ModeResult(mode=11, count=2)

In [77]:
## Finding standard deviation using numpy

std = np.std(arr_size)
std

3.7043517951488116

In [78]:
rounded_std = std.round()
std.round()

4.0

In [79]:
int_std = int(rounded_std)  ## converting the result of std into an integer value, 4.
int(rounded_std)

4

In [80]:
# class fun

In [178]:
num = [2, 3, 1, 4, 2 , 5, 6, 7, 4 , 8, 9, 7]
arr = np.array(num)
min_num = np.min(arr)
print(min_num)

1


In [82]:
max_num = np.max(arr)
print(max_num)

9


In [83]:
## addition of numbers  40 , 30,with numpy
addition = np.add(40, 30)
addition


70

In [84]:
new =np.add(addition, 45)
new

115

In [180]:
numbers = [3, 4, 5, 6, 1, 5, 8, 9, 6, 4, 2, 5]
nums = np.array((num, numbers))
nums

array([[2, 3, 1, 4, 2, 5, 6, 7, 4, 8, 9, 7],
       [3, 4, 5, 6, 1, 5, 8, 9, 6, 4, 2, 5]])

In [182]:
np.concatenate(nums)

array([2, 3, 1, 4, 2, 5, 6, 7, 4, 8, 9, 7, 3, 4, 5, 6, 1, 5, 8, 9, 6, 4,
       2, 5])

In [184]:
np.add(num, numbers)

array([ 5,  7,  6, 10,  3, 10, 14, 16, 10, 12, 11, 12])

In [186]:
nums.shape

(2, 12)

In [192]:
nums.reshape(2, 4, 3)

array([[[2, 3, 1],
        [4, 2, 5],
        [6, 7, 4],
        [8, 9, 7]],

       [[3, 4, 5],
        [6, 1, 5],
        [8, 9, 6],
        [4, 2, 5]]])

In [194]:
average_num = np.array(numbers)
mean_num = np.mean(average_num)
mean_num

4.833333333333333

In [196]:
median_num = np.median(average_num)
median_num

5.0

In [198]:
from scipy import stats
mode = stats.mode(average_num)
mode

ModeResult(mode=5, count=3)

In [204]:
mode = stats.mode(arr)
mode

ModeResult(mode=2, count=2)

In [206]:
std_dev = np.std(arr)
std_dev

2.4776781245530843

In [210]:
mean = np.mean(num)
mean

4.833333333333333

In [212]:
median = np.median(arr)
median

4.5

In [214]:
mode = stats.mode(arr)
mode

ModeResult(mode=2, count=2)

In [216]:
min = np.min(num)
min

1

In [230]:
max = np.max(arr)
max

9

In [238]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [240]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [242]:
a.size

12

In [244]:
a.shape

(3, 4)

In [246]:
a[2]

array([ 8,  9, 10, 11])

In [258]:
a[-1]

array([ 8,  9, 10, 11])

In [286]:
a = np.random.rand(2, 3, 2)
a

array([[[0.98418915, 0.27592415],
        [0.858853  , 0.83110815],
        [0.25131583, 0.19921   ]],

       [[0.84670439, 0.1802413 ],
        [0.81947194, 0.72608237],
        [0.06369855, 0.882134  ]]])

In [288]:
a[0:2, 1, :]

array([[0.858853  , 0.83110815],
       [0.81947194, 0.72608237]])